# Generated by Django 3.2 on 2023-10-15 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231016_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='site_type',
            field=models.CharField(choices=[('blog', 'Блог'), ('ecommerce', 'Интернет-магазин'), ('personal', 'Личный сайт'), ('corporate', 'Корпоративный сайт')], default='blog', max_length=20),
            preserve_default=False,
        ),
    ]
