# Generated by Django 3.2 on 2023-10-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231016_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
